"""fix_drift_transaction_id_y_presupuestos

Revision ID: 6f323c915bc9
Revises: 0012
Create Date: 2026-06-15 15:59:02.191077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f323c915bc9'
down_revision: Union[str, Sequence[str], None] = '0012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_gastos_transaction_id'), 'gastos', type_='unique')
    op.drop_index(op.f('ix_gastos_transaction_id'), table_name='gastos')
    op.create_index(op.f('ix_gastos_transaction_id'), 'gastos', ['transaction_id'], unique=True)
    op.drop_constraint(op.f('uq_ingresos_transaction_id'), 'ingresos', type_='unique')
    op.drop_index(op.f('ix_ingresos_transaction_id'), table_name='ingresos')
    op.create_index(op.f('ix_ingresos_transaction_id'), 'ingresos', ['transaction_id'], unique=True)
    op.alter_column('presupuestos', 'categoria_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('presupuestos', 'categoria_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_ingresos_transaction_id'), table_name='ingresos')
    op.create_index(op.f('ix_ingresos_transaction_id'), 'ingresos', ['transaction_id'], unique=False)
    op.create_unique_constraint(op.f('uq_ingresos_transaction_id'), 'ingresos', ['transaction_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_gastos_transaction_id'), table_name='gastos')
    op.create_index(op.f('ix_gastos_transaction_id'), 'gastos', ['transaction_id'], unique=False)
    op.create_unique_constraint(op.f('uq_gastos_transaction_id'), 'gastos', ['transaction_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
